# Generated by Django 5.1.6 on 2026-09-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Neçə illik təcrübəsi var'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='projects',
            field=models.TextField(blank=True, help_text='Bitirdiyi əsas layihələr və ya nailiyyətlər', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True, help_text='Əsas bacarıqları və ixtisas sahələri (vergüllə ayrılmış və ya qısa mətn)', null=True),
        ),
    ]
