# Generated by Django 5.1.6 on 2026-09-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_teammember_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='value',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
