# Generated by Django 5.1.6 on 2026-09-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_teammember_bio_az_teammember_bio_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio_az',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio_ru',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='projects_az',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='projects_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='projects_ru',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role_az',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role_ru',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='skills_az',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='skills_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='skills_ru',
        ),
        migrations.RemoveField(
            model_name='value',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='value',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='value',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='value',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='value',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='value',
            name='title_ru',
        ),
    ]
