# Generated by Django 5.1.6 on 2026-09-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_teammember_bio_az_remove_teammember_bio_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='projects_az',
            field=models.TextField(blank=True, help_text='Bitirdiyi əsas layihələr və ya nailiyyətlər', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='projects_en',
            field=models.TextField(blank=True, help_text='Bitirdiyi əsas layihələr və ya nailiyyətlər', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='projects_ru',
            field=models.TextField(blank=True, help_text='Bitirdiyi əsas layihələr və ya nailiyyətlər', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills_az',
            field=models.TextField(blank=True, help_text='Əsas bacarıqları və ixtisas sahələri (vergüllə ayrılmış və ya qısa mətn)', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills_en',
            field=models.TextField(blank=True, help_text='Əsas bacarıqları və ixtisas sahələri (vergüllə ayrılmış və ya qısa mətn)', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills_ru',
            field=models.TextField(blank=True, help_text='Əsas bacarıqları və ixtisas sahələri (vergüllə ayrılmış və ya qısa mətn)', null=True),
        ),
        migrations.AddField(
            model_name='value',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='value',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='value',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='value',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='value',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='value',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
