# Generated by Django 5.1.6 on 2026-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_teammember_bio_az_teammember_bio_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Bizim Hekayəmiz', help_text='Bölmənin əsas başlığı (məs: Bizim Hekayəmiz)', max_length=200)),
                ('heading_az', models.CharField(default='Bizim Hekayəmiz', help_text='Bölmənin əsas başlığı (məs: Bizim Hekayəmiz)', max_length=200, null=True)),
                ('heading_ru', models.CharField(default='Bizim Hekayəmiz', help_text='Bölmənin əsas başlığı (məs: Bizim Hekayəmiz)', max_length=200, null=True)),
                ('heading_en', models.CharField(default='Bizim Hekayəmiz', help_text='Bölmənin əsas başlığı (məs: Bizim Hekayəmiz)', max_length=200, null=True)),
                ('subheading', models.CharField(blank=True, default='WebSuper Agency', help_text='Qradiyent rəngli alt başlıq', max_length=200)),
                ('subheading_az', models.CharField(blank=True, default='WebSuper Agency', help_text='Qradiyent rəngli alt başlıq', max_length=200, null=True)),
                ('subheading_ru', models.CharField(blank=True, default='WebSuper Agency', help_text='Qradiyent rəngli alt başlıq', max_length=200, null=True)),
                ('subheading_en', models.CharField(blank=True, default='WebSuper Agency', help_text='Qradiyent rəngli alt başlıq', max_length=200, null=True)),
                ('description', models.TextField(help_text='Haqqımızda bölməsinin əsas hekayə mətni')),
                ('description_az', models.TextField(help_text='Haqqımızda bölməsinin əsas hekayə mətni', null=True)),
                ('description_ru', models.TextField(help_text='Haqqımızda bölməsinin əsas hekayə mətni', null=True)),
                ('description_en', models.TextField(help_text='Haqqımızda bölməsinin əsas hekayə mətni', null=True)),
                ('mission', models.TextField(blank=True, help_text='Missiyamız mətni', null=True)),
                ('mission_az', models.TextField(blank=True, help_text='Missiyamız mətni', null=True)),
                ('mission_ru', models.TextField(blank=True, help_text='Missiyamız mətni', null=True)),
                ('mission_en', models.TextField(blank=True, help_text='Missiyamız mətni', null=True)),
                ('image', models.ImageField(blank=True, help_text='Yan tərəfdə görünən komanda/ofis şəkili', null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'Haqqımızda Məzmunu',
                'verbose_name_plural': 'Haqqımızda Bölməsi',
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': 'Komanda Üzvü', 'verbose_name_plural': 'Komanda Üzvləri (Haqqımızda/Ana Səhifə)'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['order'], 'verbose_name': 'Dəyər', 'verbose_name_plural': 'Dəyərlərimiz (Haqqımızda)'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Saytda aktiv görünsün?'),
        ),
        migrations.AddField(
            model_name='value',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Saytda aktiv görünsün?'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Qısa tərcümeyi-hal / haqqında məlumat', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio_az',
            field=models.TextField(blank=True, help_text='Qısa tərcümeyi-hal / haqqında məlumat', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, help_text='Qısa tərcümeyi-hal / haqqında məlumat', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio_ru',
            field=models.TextField(blank=True, help_text='Qısa tərcümeyi-hal / haqqında məlumat', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(help_text='Komanda üzvünün şəkili', upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(help_text='Komanda üzvünün tam adı', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_az',
            field=models.CharField(help_text='Komanda üzvünün tam adı', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(help_text='Komanda üzvünün tam adı', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(help_text='Komanda üzvünün tam adı', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Görünmə ardıcıllığı'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='Vəzifəsi (məs: CEO & Founder, Lead Designer, Senior Developer)', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_az',
            field=models.CharField(help_text='Vəzifəsi (məs: CEO & Founder, Lead Designer, Senior Developer)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(help_text='Vəzifəsi (məs: CEO & Founder, Lead Designer, Senior Developer)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(help_text='Vəzifəsi (məs: CEO & Founder, Lead Designer, Senior Developer)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True, help_text='Əsas bacarıqları (məs: UI/UX Dizayn, Figma, Python, Django)', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills_az',
            field=models.TextField(blank=True, help_text='Əsas bacarıqları (məs: UI/UX Dizayn, Figma, Python, Django)', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills_en',
            field=models.TextField(blank=True, help_text='Əsas bacarıqları (məs: UI/UX Dizayn, Figma, Python, Django)', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills_ru',
            field=models.TextField(blank=True, help_text='Əsas bacarıqları (məs: UI/UX Dizayn, Figma, Python, Django)', null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='description',
            field=models.TextField(help_text='Dəyərin qısa izahı'),
        ),
        migrations.AlterField(
            model_name='value',
            name='description_az',
            field=models.TextField(help_text='Dəyərin qısa izahı', null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='description_en',
            field=models.TextField(help_text='Dəyərin qısa izahı', null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='description_ru',
            field=models.TextField(help_text='Dəyərin qısa izahı', null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='icon',
            field=models.CharField(help_text='FontAwesome ikonu (məs: fas fa-lightbulb, fas fa-handshake, fas fa-gem)', max_length=50),
        ),
        migrations.AlterField(
            model_name='value',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Görünmə ardıcıllığı'),
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(help_text='Dəyərin adı (məs: İnnovasiya, Etibarlılıq, Keyfiyyət)', max_length=100),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_az',
            field=models.CharField(help_text='Dəyərin adı (məs: İnnovasiya, Etibarlılıq, Keyfiyyət)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_en',
            field=models.CharField(help_text='Dəyərin adı (məs: İnnovasiya, Etibarlılıq, Keyfiyyət)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_ru',
            field=models.CharField(help_text='Dəyərin adı (məs: İnnovasiya, Etibarlılıq, Keyfiyyət)', max_length=100, null=True),
        ),
    ]
