# Generated by Django 5.1.6 on 2026-09-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='customer_name',
            field=models.CharField(default='Qonaq', max_length=60, verbose_name='Müştəri Adı'),
        ),
    ]
