# Generated by Django 5.1.6 on 2026-09-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_category_name_az_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_quote_az',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_quote_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_quote_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem_statement_az',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem_statement_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem_statement_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='result_az',
        ),
        migrations.RemoveField(
            model_name='project',
            name='result_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='result_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solution_az',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solution_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solution_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_ru',
        ),
    ]
