# Generated by Django 5.1.6 on 2026-09-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_category_name_az_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Layihə Kateqoriyası', 'verbose_name_plural': 'Layihə Kateqoriyaları'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Portfolio Layihəsi', 'verbose_name_plural': 'Portfolio Layihələri'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order'], 'verbose_name': 'Layihə Qalereya Şəkili', 'verbose_name_plural': 'Layihə Qalereyası Şəkilləri'},
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Saytda aktiv görünsün?'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='Layihənin canlı veb sayt / tətbiq linki', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Kateqoriyanın adı (məs: Veb İnkişaf, Mobil Tətbiq, Brendinq)', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_az',
            field=models.CharField(help_text='Kateqoriyanın adı (məs: Veb İnkişaf, Mobil Tətbiq, Brendinq)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Kateqoriyanın adı (məs: Veb İnkişaf, Mobil Tətbiq, Brendinq)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Kateqoriyanın adı (məs: Veb İnkişaf, Mobil Tətbiq, Brendinq)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL üçün unikal identifikator', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(help_text='Aid olduğu kateqoriya', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='Müştərinin adı / şirkət', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_quote',
            field=models.TextField(blank=True, help_text='Müştərinin rəyi', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_quote_az',
            field=models.TextField(blank=True, help_text='Müştərinin rəyi', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_quote_en',
            field=models.TextField(blank=True, help_text='Müştərinin rəyi', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_quote_ru',
            field=models.TextField(blank=True, help_text='Müştərinin rəyi', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(help_text='Layihənin əsas üzlük şəkili', upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Layihə haqqında ümumi məlumat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_az',
            field=models.TextField(help_text='Layihə haqqında ümumi məlumat', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(help_text='Layihə haqqında ümumi məlumat', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=models.TextField(help_text='Layihə haqqında ümumi məlumat', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Görünmə ardıcıllığı'),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='Qarşıya qoyulan problem', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem_statement_az',
            field=models.TextField(blank=True, help_text='Qarşıya qoyulan problem', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem_statement_en',
            field=models.TextField(blank=True, help_text='Qarşıya qoyulan problem', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem_statement_ru',
            field=models.TextField(blank=True, help_text='Qarşıya qoyulan problem', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True, help_text='Əldə olunan nəticə', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='result_az',
            field=models.TextField(blank=True, help_text='Əldə olunan nəticə', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='result_en',
            field=models.TextField(blank=True, help_text='Əldə olunan nəticə', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='result_ru',
            field=models.TextField(blank=True, help_text='Əldə olunan nəticə', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='URL üçün unikal identifikator', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='Təqdim etdiyimiz həll', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution_az',
            field=models.TextField(blank=True, help_text='Təqdim etdiyimiz həll', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution_en',
            field=models.TextField(blank=True, help_text='Təqdim etdiyimiz həll', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution_ru',
            field=models.TextField(blank=True, help_text='Təqdim etdiyimiz həll', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='İstifadə olunan texnologiyalar (vergüllə ayrılmış, məs: Python, Django, React)', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Layihənin adı', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_az',
            field=models.CharField(help_text='Layihənin adı', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_en',
            field=models.CharField(help_text='Layihənin adı', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_ru',
            field=models.CharField(help_text='Layihənin adı', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Əlavə qalereya şəkili', upload_to='portfolio/gallery/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Şəkillərin qalereyadakı ardıcıllığı'),
        ),
    ]
