# Generated by Django 5.1.6 on 2026-09-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Müraciət Məktubu', 'verbose_name_plural': 'Gələn Müraciətlər'},
        ),
    ]
