# Generated by Django 5.1.6 on 2026-09-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gələn Mesaj', 'verbose_name_plural': 'Gələn Mesajlar (Əlaqə Formu)'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Göndərilmə Tarixi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='Müraciət edənin əlaqə e-poçtu', max_length=254, verbose_name='E-poçt Ünvanı'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Mesaj oxunubsa işarələyin', verbose_name='Oxundu'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='Müraciət edən şəxsin göndərdiyi ətraflı mesaj mətni', verbose_name='Mesaj Mətni'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Müraciət edən şəxsin tam adı', max_length=150, verbose_name='Ad və Soyad'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Əlaqə telefon nömrəsi', max_length=50, null=True, verbose_name='Telefon Nömrəsi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(help_text='Müraciətin qısa mövzusu', max_length=200, verbose_name='Müraciət Mövzusu'),
        ),
    ]
