# Generated by Django 6.1.1 on 2026-09-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarix')),
            ],
            options={
                'verbose_name': 'Canlı Çat Mesajı',
                'verbose_name_plural': 'Canlı Çat Mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
