# Generated by Django 5.1.6 on 2026-09-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_livechatmessage'),
        ('home', '0012_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Əlaqə Tənzimləmələri',
                'verbose_name_plural': 'Əlaqə Tənzimləmələri (Xəritə, Nömrə)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.sitesettings',),
        ),
    ]
