# Generated by Django 5.1.6 on 2026-09-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_az_post_content_en_post_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_az',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_az',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_ru',
        ),
    ]
