# Generated by Django 5.1.6 on 2026-09-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_content_az_post_content_en_post_content_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Məqalə (Yazı)', 'verbose_name_plural': 'Blog Məqalələri'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Məqalə Kateqoriyası', 'verbose_name_plural': 'Məqalə Kateqoriyaları'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Teq', 'verbose_name_plural': 'Teqlər'},
        ),
    ]
