# Generated by Django 5.1.6 on 2026-09-22 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_alter_postcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Məqalə', 'verbose_name_plural': 'Blog Məqalələri'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Məqaləni yazan istifadəçi', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Müəllif'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(help_text='Aid olduğu mövzu/kateqoriya', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.postcategory', verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Məqalənin tam oxunan geniş mətni', verbose_name='Məqalənin Tam Mətni'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_az',
            field=models.TextField(help_text='Məqalənin tam oxunan geniş mətni', null=True, verbose_name='Məqalənin Tam Mətni'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(help_text='Məqalənin tam oxunan geniş mətni', null=True, verbose_name='Məqalənin Tam Mətni'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ru',
            field=models.TextField(help_text='Məqalənin tam oxunan geniş mətni', null=True, verbose_name='Məqalənin Tam Mətni'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(help_text='Məqalə kartında və səhifəsində görünən əsas şəkil', upload_to='blog/', verbose_name='Əsas Şəkil (Cover)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dərc Tarixi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(help_text='Kartın üzərində görünən 1-2 cümləlik qısa xülasə', max_length=300, verbose_name='Qısa Məzmun (Excerpt)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_az',
            field=models.TextField(help_text='Kartın üzərində görünən 1-2 cümləlik qısa xülasə', max_length=300, null=True, verbose_name='Qısa Məzmun (Excerpt)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(help_text='Kartın üzərində görünən 1-2 cümləlik qısa xülasə', max_length=300, null=True, verbose_name='Qısa Məzmun (Excerpt)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_ru',
            field=models.TextField(help_text='Kartın üzərində görünən 1-2 cümləlik qısa xülasə', max_length=300, null=True, verbose_name='Qısa Məzmun (Excerpt)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Xüsusi vurğulanmış/seçilmiş kimi göstərilsin?', verbose_name='Seçilmiş Məqalə'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=5, help_text='Təxmini oxuma vaxtı', verbose_name='Oxuma Müddəti (dəqiqə)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Məqalə linki (məs: muasir-veb-dizayn-trendleri)', unique=True, verbose_name='URL Keçid (Slug)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='Teqlər (Açar sözlər)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Məqalənin əsas başlığı (məs: Müasir Veb Dizayn Trendləri)', max_length=200, verbose_name='Məqalə Başlığı'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_az',
            field=models.CharField(help_text='Məqalənin əsas başlığı (məs: Müasir Veb Dizayn Trendləri)', max_length=200, null=True, verbose_name='Məqalə Başlığı'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(help_text='Məqalənin əsas başlığı (məs: Müasir Veb Dizayn Trendləri)', max_length=200, null=True, verbose_name='Məqalə Başlığı'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(help_text='Məqalənin əsas başlığı (məs: Müasir Veb Dizayn Trendləri)', max_length=200, null=True, verbose_name='Məqalə Başlığı'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Yenilənmə Tarixi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Baxış Sayı'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(help_text='Məqalə kateqoriyası (məs: Texnologiya, Dizayn, Proqramlaşdırma)', max_length=100, verbose_name='Kateqoriya Adı'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name_az',
            field=models.CharField(help_text='Məqalə kateqoriyası (məs: Texnologiya, Dizayn, Proqramlaşdırma)', max_length=100, null=True, verbose_name='Kateqoriya Adı'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name_en',
            field=models.CharField(help_text='Məqalə kateqoriyası (məs: Texnologiya, Dizayn, Proqramlaşdırma)', max_length=100, null=True, verbose_name='Kateqoriya Adı'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name_ru',
            field=models.CharField(help_text='Məqalə kateqoriyası (məs: Texnologiya, Dizayn, Proqramlaşdırma)', max_length=100, null=True, verbose_name='Kateqoriya Adı'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(help_text='Avtomatik doldurulur və ya unikal latın qısaltması', unique=True, verbose_name='URL Keçid (Slug)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Açar söz / teq (məs: web, ui, mobile)', max_length=50, verbose_name='Teq Adı'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_az',
            field=models.CharField(help_text='Açar söz / teq (məs: web, ui, mobile)', max_length=50, null=True, verbose_name='Teq Adı'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(help_text='Açar söz / teq (məs: web, ui, mobile)', max_length=50, null=True, verbose_name='Teq Adı'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(help_text='Açar söz / teq (məs: web, ui, mobile)', max_length=50, null=True, verbose_name='Teq Adı'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL Keçid (Slug)'),
        ),
    ]
