# Generated by Django 5.1.6 on 2026-09-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Rəqəmsal Dünyada İz Buraxın', max_length=200)),
                ('subtitle', models.TextField(default='Müasir texnologiyalar və innovativ dizaynla biznesinizi inkişaf etdiririk. Sizin uğurunuz, bizim prioritetimizdir.')),
                ('button1_text', models.CharField(default='Layihəyə Başla', max_length=50)),
                ('button1_link', models.CharField(default='#contact', max_length=200)),
                ('button2_text', models.CharField(default='İşlərimiz', max_length=50)),
                ('button2_link', models.CharField(default='#portfolio', max_length=200)),
            ],
            options={
                'verbose_name': 'Hero Content',
                'verbose_name_plural': 'Hero Content',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(help_text='Məs: 500₼ və ya Xüsusi', max_length=50)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Hər xüsusiyyəti yeni sətirdə yazın (Enter-lə ayırın).')),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Qiymət Planı',
                'verbose_name_plural': 'Qiymət Planları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='Məsələn: fa-solid fa-code', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='showcase/')),
                ('link', models.CharField(default='#', max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Showcase Elementi',
                'verbose_name_plural': 'Showcase Elementləri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Baku, Azerbaijan', max_length=200)),
                ('phone', models.CharField(default='+994 50 000 00 00', max_length=50)),
                ('email', models.EmailField(default='info@websuper.az', max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sayt Tənzimləmələri',
                'verbose_name_plural': 'Sayt Tənzimləmələri',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='Məsələn: fa-solid fa-users', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ['order'],
            },
        ),
    ]
