# Generated by Django 5.1.6 on 2026-09-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='gradient_text',
            field=models.CharField(default='İz Buraxın', help_text='Başlığın qradiyent rəngli ikinci sətri', max_length=200),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='button1_link',
            field=models.CharField(default='/contact/', max_length=200),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='button2_link',
            field=models.CharField(default='/portfolio/', max_length=200),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='button2_text',
            field=models.CharField(default='Portfolioya Bax', max_length=50),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='title',
            field=models.CharField(default='Rəqəmsal Dünyada', max_length=200),
        ),
    ]
