# Generated by Django 5.1.6 on 2026-09-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_herocontent_gradient_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='button1_text_az',
            field=models.CharField(default='Layihəyə Başla', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='button1_text_en',
            field=models.CharField(default='Layihəyə Başla', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='button1_text_ru',
            field=models.CharField(default='Layihəyə Başla', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='button2_text_az',
            field=models.CharField(default='Portfolioya Bax', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='button2_text_en',
            field=models.CharField(default='Portfolioya Bax', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='button2_text_ru',
            field=models.CharField(default='Portfolioya Bax', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='gradient_text_az',
            field=models.CharField(default='İz Buraxın', help_text='Başlığın qradiyent rəngli ikinci sətri', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='gradient_text_en',
            field=models.CharField(default='İz Buraxın', help_text='Başlığın qradiyent rəngli ikinci sətri', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='gradient_text_ru',
            field=models.CharField(default='İz Buraxın', help_text='Başlığın qradiyent rəngli ikinci sətri', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='subtitle_az',
            field=models.TextField(default='Müasir texnologiyalar və innovativ dizaynla biznesinizi inkişaf etdiririk. Sizin uğurunuz, bizim prioritetimizdir.', null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='subtitle_en',
            field=models.TextField(default='Müasir texnologiyalar və innovativ dizaynla biznesinizi inkişaf etdiririk. Sizin uğurunuz, bizim prioritetimizdir.', null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='subtitle_ru',
            field=models.TextField(default='Müasir texnologiyalar və innovativ dizaynla biznesinizi inkişaf etdiririk. Sizin uğurunuz, bizim prioritetimizdir.', null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='title_az',
            field=models.CharField(default='Rəqəmsal Dünyada', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='title_en',
            field=models.CharField(default='Rəqəmsal Dünyada', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='title_ru',
            field=models.CharField(default='Rəqəmsal Dünyada', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='features_az',
            field=models.TextField(help_text='Hər xüsusiyyəti yeni sətirdə yazın (Enter-lə ayırın).', null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='features_en',
            field=models.TextField(help_text='Hər xüsusiyyəti yeni sətirdə yazın (Enter-lə ayırın).', null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='features_ru',
            field=models.TextField(help_text='Hər xüsusiyyəti yeni sətirdə yazın (Enter-lə ayırın).', null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_az',
            field=models.CharField(default='Baku, Azerbaijan', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(default='Baku, Azerbaijan', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(default='Baku, Azerbaijan', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
