# Generated by Django 5.1.6 on 2026-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_herocontent_button1_text_az_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herocontent',
            options={'verbose_name': 'Əsas Hero Başlığı', 'verbose_name_plural': 'Ana Səhifə Hero Bölməsi'},
        ),
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['order'], 'verbose_name': 'Qiymət Paketi', 'verbose_name_plural': 'Qiymət Paketləri (Tariflər)'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Xidmət', 'verbose_name_plural': 'Xidmətlər Bölməsi'},
        ),
        migrations.AlterModelOptions(
            name='showcaseitem',
            options={'ordering': ['order'], 'verbose_name': 'Ana Səhifə Slaydı', 'verbose_name_plural': 'Ana Səhifə Slayderi'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Sayt Əlaqə & Sosial Media Tənzimləmələri', 'verbose_name_plural': 'Sayt Ümumi Tənzimləmələri'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['order'], 'verbose_name': 'Statistika Rəqəmi', 'verbose_name_plural': 'Statistika Bloku (150+, 50+ və s.)'},
        ),
        migrations.RemoveField(
            model_name='showcaseitem',
            name='link',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Saytda aktiv görünsün?'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Saytda aktiv görünsün?'),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='button_text',
            field=models.CharField(default='Ətraflı Bax', help_text='Düymə mətni', max_length=50),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='button_text_az',
            field=models.CharField(default='Ətraflı Bax', help_text='Düymə mətni', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='button_text_en',
            field=models.CharField(default='Ətraflı Bax', help_text='Düymə mətni', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='button_text_ru',
            field=models.CharField(default='Ətraflı Bax', help_text='Düymə mətni', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='button_url',
            field=models.CharField(default='/portfolio/', help_text='Düyməyə klik edildikdə açılacaq link', max_length=200),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Saytda aktiv görünsün?'),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Qısa alt başlıq və ya istiqamətlər (məs: iOS və Android, Nativ Həllər)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='subtitle_az',
            field=models.CharField(blank=True, help_text='Qısa alt başlıq və ya istiqamətlər (məs: iOS və Android, Nativ Həllər)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Qısa alt başlıq və ya istiqamətlər (məs: iOS və Android, Nativ Həllər)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='subtitle_ru',
            field=models.CharField(blank=True, help_text='Qısa alt başlıq və ya istiqamətlər (məs: iOS və Android, Nativ Həllər)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Saytda aktiv görünsün?'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(help_text='Paketin qısa izahı'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='description_az',
            field=models.TextField(help_text='Paketin qısa izahı', null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='description_en',
            field=models.TextField(help_text='Paketin qısa izahı', null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='description_ru',
            field=models.TextField(help_text='Paketin qısa izahı', null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="'Ən Populyar' etiketi göstərilsin?"),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(help_text='Paketin adı (məs: Başlanğıc, Standart, Premium)', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name_az',
            field=models.CharField(help_text='Paketin adı (məs: Başlanğıc, Standart, Premium)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name_en',
            field=models.CharField(help_text='Paketin adı (məs: Başlanğıc, Standart, Premium)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name_ru',
            field=models.CharField(help_text='Paketin adı (məs: Başlanğıc, Standart, Premium)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='order',
            field=models.IntegerField(default=0, help_text='Görünmə ardıcıllığı'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.CharField(help_text='Qiymət (məs: 500 AZN-dən, 1200 AZN-dən)', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Xidmət haqqında qısa izah'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_az',
            field=models.TextField(help_text='Xidmət haqqında qısa izah', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(help_text='Xidmət haqqında qısa izah', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.TextField(help_text='Xidmət haqqında qısa izah', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(help_text='FontAwesome ikonu (məs: fa-solid fa-code, fa-solid fa-mobile-screen)', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Görünmə ardıcıllığı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Xidmətin adı (məs: Veb İnkişaf, Mobil Tətbiq)', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_az',
            field=models.CharField(help_text='Xidmətin adı (məs: Veb İnkişaf, Mobil Tətbiq)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(help_text='Xidmətin adı (məs: Veb İnkişaf, Mobil Tətbiq)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ru',
            field=models.CharField(help_text='Xidmətin adı (məs: Veb İnkişaf, Mobil Tətbiq)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='description',
            field=models.TextField(help_text='Kartın üzərində görünən izah mətni'),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='description_az',
            field=models.TextField(help_text='Kartın üzərində görünən izah mətni', null=True),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='description_en',
            field=models.TextField(help_text='Kartın üzərində görünən izah mətni', null=True),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='description_ru',
            field=models.TextField(help_text='Kartın üzərində görünən izah mətni', null=True),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='image',
            field=models.ImageField(help_text='Slaydın arxa fon şəkili', upload_to='showcase/'),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Görünmə ardıcıllığı'),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='title',
            field=models.CharField(help_text='Slaydın əsas başlığı (məs: Veb Tətbiqlər, Mobil Tətbiqlər, Kreativ Brendinq)', max_length=150),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='title_az',
            field=models.CharField(help_text='Slaydın əsas başlığı (məs: Veb Tətbiqlər, Mobil Tətbiqlər, Kreativ Brendinq)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='title_en',
            field=models.CharField(help_text='Slaydın əsas başlığı (məs: Veb Tətbiqlər, Mobil Tətbiqlər, Kreativ Brendinq)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='title_ru',
            field=models.CharField(help_text='Slaydın əsas başlığı (məs: Veb Tətbiqlər, Mobil Tətbiqlər, Kreativ Brendinq)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Baku, Azerbaijan', help_text='Ünvan mətni', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_az',
            field=models.CharField(default='Baku, Azerbaijan', help_text='Ünvan mətni', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(default='Baku, Azerbaijan', help_text='Ünvan mətni', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(default='Baku, Azerbaijan', help_text='Ünvan mətni', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='info@websuper.az', help_text='Əlaqə e-poçt ünvanı', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook səhifə linki', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profil linki', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profil linki', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+994 50 000 00 00', help_text='Əlaqə nömrəsi', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter / X linki', null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='icon_class',
            field=models.CharField(blank=True, help_text='İstəyə bağlı FontAwesome ikonu (məs: fa-solid fa-users)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label',
            field=models.CharField(help_text='Statistikanın izahı (məs: Layihə, Müştəri, İl Təcrübə, Dəstək)', max_length=100),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label_az',
            field=models.CharField(help_text='Statistikanın izahı (məs: Layihə, Müştəri, İl Təcrübə, Dəstək)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label_en',
            field=models.CharField(help_text='Statistikanın izahı (məs: Layihə, Müştəri, İl Təcrübə, Dəstək)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label_ru',
            field=models.CharField(help_text='Statistikanın izahı (məs: Layihə, Müştəri, İl Təcrübə, Dəstək)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='number',
            field=models.CharField(help_text='Statistika rəqəmi (məs: 150+, 50+, 5+, 24/7)', max_length=50),
        ),
        migrations.AlterField(
            model_name='stat',
            name='order',
            field=models.IntegerField(default=0, help_text='Görünmə ardıcıllığı'),
        ),
    ]
