# Generated by Django 5.1.6 on 2026-09-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_herocontent_options_alter_pricingplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Layihənizi Bu Gün Başladaq', help_text='Böyük əsas başlıq (məs: Layihənizi Bu Gün Başladaq)', max_length=200, verbose_name='Bölmə Başlığı')),
                ('title_az', models.CharField(default='Layihənizi Bu Gün Başladaq', help_text='Böyük əsas başlıq (məs: Layihənizi Bu Gün Başladaq)', max_length=200, null=True, verbose_name='Bölmə Başlığı')),
                ('title_ru', models.CharField(default='Layihənizi Bu Gün Başladaq', help_text='Böyük əsas başlıq (məs: Layihənizi Bu Gün Başladaq)', max_length=200, null=True, verbose_name='Bölmə Başlığı')),
                ('title_en', models.CharField(default='Layihənizi Bu Gün Başladaq', help_text='Böyük əsas başlıq (məs: Layihənizi Bu Gün Başladaq)', max_length=200, null=True, verbose_name='Bölmə Başlığı')),
                ('subtitle', models.TextField(default='Peşəkar komandamızla birlikdə biznesinizi rəqəmsal zirvəyə qaldırın.', help_text='Başlığın altındakı izah mətni', verbose_name='Alt İzah Mətni')),
                ('subtitle_az', models.TextField(default='Peşəkar komandamızla birlikdə biznesinizi rəqəmsal zirvəyə qaldırın.', help_text='Başlığın altındakı izah mətni', null=True, verbose_name='Alt İzah Mətni')),
                ('subtitle_ru', models.TextField(default='Peşəkar komandamızla birlikdə biznesinizi rəqəmsal zirvəyə qaldırın.', help_text='Başlığın altındakı izah mətni', null=True, verbose_name='Alt İzah Mətni')),
                ('subtitle_en', models.TextField(default='Peşəkar komandamızla birlikdə biznesinizi rəqəmsal zirvəyə qaldırın.', help_text='Başlığın altındakı izah mətni', null=True, verbose_name='Alt İzah Mətni')),
                ('button_text', models.CharField(default='Bizimlə Əlaqə', help_text='Düymə üzərində görünən yazı', max_length=50, verbose_name='Düymə Mətni')),
                ('button_text_az', models.CharField(default='Bizimlə Əlaqə', help_text='Düymə üzərində görünən yazı', max_length=50, null=True, verbose_name='Düymə Mətni')),
                ('button_text_ru', models.CharField(default='Bizimlə Əlaqə', help_text='Düymə üzərində görünən yazı', max_length=50, null=True, verbose_name='Düymə Mətni')),
                ('button_text_en', models.CharField(default='Bizimlə Əlaqə', help_text='Düymə üzərində görünən yazı', max_length=50, null=True, verbose_name='Düymə Mətni')),
                ('button_url', models.CharField(default='/contact/', help_text='Düyməyə klik edildikdə açılacaq link (məs: /contact/)', max_length=200, verbose_name='Düymə Linki (URL)')),
                ('background_image', models.ImageField(blank=True, help_text='İstəyə bağlı: Xüsusi arxa fon şəkili (boş qalarsa əllər olan yaşıl şablon qalır)', null=True, upload_to='cta/', verbose_name='Arxa Fon Şəkili')),
            ],
            options={
                'verbose_name': 'Son CTA Bölməsi',
                'verbose_name_plural': 'Son CTA Bölməsi (Layihənizi Başladaq)',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(default='1', help_text='Mərhələnin nömrəsi (məs: 1, 2, 3, 4)', max_length=10, verbose_name='Mərhələ Nömrəsi')),
                ('title', models.CharField(help_text='Mərhələnin adı (məs: Kəşfiyyat, Dizayn, Development, Təhvil & Dəstək)', max_length=100, verbose_name='Mərhələ Başlığı')),
                ('title_az', models.CharField(help_text='Mərhələnin adı (məs: Kəşfiyyat, Dizayn, Development, Təhvil & Dəstək)', max_length=100, null=True, verbose_name='Mərhələ Başlığı')),
                ('title_ru', models.CharField(help_text='Mərhələnin adı (məs: Kəşfiyyat, Dizayn, Development, Təhvil & Dəstək)', max_length=100, null=True, verbose_name='Mərhələ Başlığı')),
                ('title_en', models.CharField(help_text='Mərhələnin adı (məs: Kəşfiyyat, Dizayn, Development, Təhvil & Dəstək)', max_length=100, null=True, verbose_name='Mərhələ Başlığı')),
                ('description', models.TextField(help_text='Mərhələ haqqında qısa izah mətni', verbose_name='Mərhələ İzahı')),
                ('description_az', models.TextField(help_text='Mərhələ haqqında qısa izah mətni', null=True, verbose_name='Mərhələ İzahı')),
                ('description_ru', models.TextField(help_text='Mərhələ haqqında qısa izah mətni', null=True, verbose_name='Mərhələ İzahı')),
                ('description_en', models.TextField(help_text='Mərhələ haqqında qısa izah mətni', null=True, verbose_name='Mərhələ İzahı')),
                ('order', models.IntegerField(default=0, help_text='Görünmə ardıcıllığı', verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, help_text='Saytda aktiv görünsün?', verbose_name='Aktivdir')),
            ],
            options={
                'verbose_name': 'İş Prosesi Mərhələsi',
                'verbose_name_plural': 'İş Prosesimiz Mərhələləri (1, 2, 3, 4)',
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Xidmət', 'verbose_name_plural': 'Xidmətlərimiz Bölməsi (3 Əsas Kart)'},
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Xidmət haqqında qısa izah mətni', verbose_name='Xidmətin İzahı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_az',
            field=models.TextField(help_text='Xidmət haqqında qısa izah mətni', null=True, verbose_name='Xidmətin İzahı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(help_text='Xidmət haqqında qısa izah mətni', null=True, verbose_name='Xidmətin İzahı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.TextField(help_text='Xidmət haqqında qısa izah mətni', null=True, verbose_name='Xidmətin İzahı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fas fa-laptop-code', help_text='FontAwesome ikonu (məs: fas fa-laptop-code, fas fa-mobile-alt, fas fa-paint-brush)', max_length=50, verbose_name='İkon Kodu (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Saytda aktiv olaraq görünsün?', verbose_name='Aktivdir'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Görünmə ardıcıllığı', verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Xidmətin adı (məs: Veb İnkişaf, Mobil Tətbiq, UI/UX Dizayn)', max_length=100, verbose_name='Xidmətin Adı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_az',
            field=models.CharField(help_text='Xidmətin adı (məs: Veb İnkişaf, Mobil Tətbiq, UI/UX Dizayn)', max_length=100, null=True, verbose_name='Xidmətin Adı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(help_text='Xidmətin adı (məs: Veb İnkişaf, Mobil Tətbiq, UI/UX Dizayn)', max_length=100, null=True, verbose_name='Xidmətin Adı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ru',
            field=models.CharField(help_text='Xidmətin adı (məs: Veb İnkişaf, Mobil Tətbiq, UI/UX Dizayn)', max_length=100, null=True, verbose_name='Xidmətin Adı'),
        ),
    ]
