# Generated by Django 5.1.6 on 2026-09-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ctabanner_processstep_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='WhatsApp nömrəsi və ya linki (məsələn: https://wa.me/994501234567)', null=True),
        ),
    ]
