# Generated by Django 5.1.6 on 2026-09-23 17:42

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sitesettings_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_image',
            field=models.ImageField(blank=True, help_text='Haqqımızda səhifəsinin arxa fon şəkli (Max 5MB. Format: jpg, png, webp)', null=True, upload_to='hero_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), home.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_hero_image',
            field=models.ImageField(blank=True, help_text='Blog səhifəsinin arxa fon şəkli (Max 5MB. Format: jpg, png, webp)', null=True, upload_to='hero_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), home.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hero_image',
            field=models.ImageField(blank=True, help_text='Əlaqə səhifəsinin arxa fon şəkli (Max 5MB. Format: jpg, png, webp)', null=True, upload_to='hero_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), home.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_hero_image',
            field=models.ImageField(blank=True, help_text='Portfolio səhifəsinin arxa fon şəkli (Max 5MB. Format: jpg, png, webp)', null=True, upload_to='hero_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), home.models.validate_image_size]),
        ),
    ]
