# Generated by Django 5.1.6 on 2026-09-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sitesettings_about_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter',
        ),
    ]
