# Generated by Django 5.1.6 on 2026-09-23 17:58

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_sitesettings_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cta_section_bg_image',
            field=models.ImageField(blank=True, help_text='Ana səhifə - CTA (Layihənizi Başladaq) bölməsinin fon şəkli (Max 5MB. Format: jpg, png, webp)', null=True, upload_to='hero_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), home.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_section_bg_image',
            field=models.ImageField(blank=True, help_text='Ana səhifə - İş Prosesimiz bölməsinin fon şəkli (Max 5MB. Format: jpg, png, webp)', null=True, upload_to='hero_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), home.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stats_section_bg_image',
            field=models.ImageField(blank=True, help_text='Ana səhifə - Statistika bölməsinin fon şəkli (Max 5MB. Format: jpg, png, webp)', null=True, upload_to='hero_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), home.models.validate_image_size]),
        ),
    ]
