# Generated by Django 5.1.6 on 2026-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sitesettings_cta_section_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d194473.42999433604!2d49.71487679318182!3d40.394508493134114!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40307d6bd6211cf9%3A0x343f6b5e7ae56c6b!2sBaku%2C%20Azerbaijan!5e0!3m2!1sen!2s!4v1690000000000!5m2!1sen!2s', help_text="Google Maps 'Embed' (Yerləşdirmə) linki. Xəritədə Share -> Embed a map hissəsindən 'src' daxilindəki linki kopyalayın."),
        ),
    ]
